### ISSUE TITLE
When a user recipe is deleted, the modify and delete buttons continue to be active despite nothing selected

### ISSUE THREAD

**Issue by logantner** [JERK-Chicken/jerk-frontend#14]
┆Issue is synchronized with this [Trello card](https://trello.com/c/Ngc0KneQ) by [Unito](https://www.unito.io/learn-more)

**Comment by jsbell406** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When a user recipe is deleted, the modify and delete buttons continue to be active despite nothing selected](https://trello.com/c/uoKHX5GQ/68-when-a-user-recipe-is-deleted-the-modify-and-delete-buttons-continue-to-be-active-despite-nothing-selected)
